### ISSUE TITLE
Handle uncertainty for coding fields

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#11]
Could be for every item, for particular items, or for groups of items.  Probably could be implemented in current DB structure (as separate and arbitrary "variable" types), linked to corresponding items elsewhere (or by name, though that's dubious).  As to whether it *should* be stored like that... needs further thought.

**Comment by davidskalinder** [comment]
@olderwoman, @matthewsmorgan, @limchaeyoon, do y'all have strong opinions on the first sentence of my original post here?  That is, do we want coders to have the ability to indicate uncertainty for every single field, for particular fields only, or for groups of fields (something like "Don't know about at least one Yes/No answer")?

**Comment by olderwoman** [comment]
I’ll try an email response. Instructions for screen out is that they should check the box only if they are certain. If uncertain they should code. Alternate approach: two columns certain uncertain. The 0 represents a radio button

Not marking events because (check all that apply):
                                                 Certain        Maybe
all events outside US;                   0                  0
all events prior to 1980;               0                  0
no protest event;                         0                  0
no Black participants or issues.    0                  0

If you are CERTAIN of at least one of these, explain why in the ‘event description’ box and do not mark event text. If you are uncertain, mark text for the events you are uncertain about.

**Comment by davidskalinder** [comment]
Hey, the email worked!  (Albeit with some PII in the reply fields, annoyingly, which I've taken out.)

But as far as the substance goes: I think your reply is more relevant to issue #5?  What I'm wondering about here is how to handle it when coders wish to mark, e.g., that they're uncertain about what date an event occurred, or what the location was.  It seems indeed that it might be valuable for pass 1 coders to do this for many bits of information, since that would let pass 2 coders quickly find the parts that require further attention.  I think that's a different issue than information about why the article was screened out entirely, which is what #5 is about...

**Comment by olderwoman** [comment]
Trouble with the email notifications is that it is hard  to figure out from them where to reply unless you just use email. I agree that uncertainty & comments need to be liberally available. Unfortunately, without cluttering up the interface too much.

**Comment by davidskalinder** [comment]
> Trouble with the email notifications is that it is hard to figure out from them where to reply unless you just use email. I agree that uncertainty & comments need to be liberally available. Unfortunately, without cluttering up the interface too much.

Yeah, that's where I am too.  @matthewsmorgan, do you have a strong sense of where the balance should be based on your pass 2 work?  If not then I can have a crack at putting them (nearly) everywhere and we can then assess the clutter and cut it back if necessary...

**Comment by davidskalinder** [comment]
So I thought of another option for this one: after every group of items, we could put a text box that says "Which if any of the above items needs special review?"

Pros to this that I can think of are:

1. Much more space-efficient than an uncertainty check-box for every single item
2. Dramatically easier to implement than check-boxes for every single item (probably a couple hours' vs. many days' work)
3. We'd get much more specific info than we would with just one check-box to indicate uncertainty for an entire section of questions, or for an entire event or article.

Cons I can think of:

1. Coders might forget to fill this in for some items
2. The open-text would require cleaning to be useful in pass 2 (though hopefully this wouldn't be too bad?)
3. A little slower to code than check-boxes since it requires some typing
4. Might create some extra annoyance when coders fill in prompts in a different order than the UI presents them?

@olderwoman / @matthewsmorgan, does this approach sound sensible to y'all?

**Comment by olderwoman** [comment]
I like this. I don't see a problem with it being left blank and additional detail about why they are uncertain is almost always useful.  Not quite sure what con #4 means in practice as I skip around when coding.

**Comment by davidskalinder** [comment]
> I like this. I don't see a problem with it being left blank and additional detail about why they are uncertain is almost always useful.

Yeah, so presumably if they're not uncertain then they'd leave it blank?  Mind you, my intention with this was to capture what they were uncertain about rather than why; if they start putting the whys in then cleaning this field probably gets more difficult (and I think the what usually makes the why clear anyway)...  But maybe even if they go crazy with it cleaning wouldn't be too bad?

> Not quite sure what con #4 means in practice as I skip around when coding.

Yeah, I think that is what I mean -- if I code two things from the yes/no section, then the date, then another two from yes/no, then it might be tough to remember that I was uncertain about the second yes/no item.  I'd have to either fill in the "don't know" field at the bottom of the section as soon as I get to the item I'm unsure about, or remember both to use the field afterward and to remember which item I needed it for.  My hope is that this awkwardness would be slight enough to justify the positives though...

**Comment by olderwoman** [comment]
Not clear what "cleaning" you are concerned about doing with the uncertain field. Why would the field need to be cleaned?

**Comment by davidskalinder** [comment]
So if we had check boxes next to every item, then we wouldn't need to clean the uncertainty info.  We'd just get a column in the data called something like "counter_protest_uncertain" marked TRUE whenever the coder clicked the uncertainty check-box next to the "Counter-protest" item.

If we put a "Which if any of the above items needs special review?" under the "Is/does this event" fields, we'd get a column called something like "which_items_uncertain" with entries like "Not sure if a counter-protest" or "Might be a counter-protest".

Ideally, it'd be nice to use whatever uncertainty info we collect to do things like call up a list of all possible counter-protests that need checking in pass 2.  With one check-box per item, we could do that immediately; with a text-box we could still do it, but the "which_items_uncertain" column would have to be cleaned...  But of course let me know if you had something else in mind here, maybe I'm missing something!

**Comment by olderwoman** [comment]
I don't see a way to resolve this without testing the tradeoffs. Pass 2 coding will also have the ability to flag problematic cases but will have been able to resolve a lot of the Pass 1 confusions. @matthewsmorgan may have thoughts on this as well

**Comment by matthewsmorgan** [comment]
I think the "Which if any of the above items needs special review?" option would work well. My sense, from what you are describing, is that this would work kind of like a general flag for Pass 1. I like that this functionality would allow Pass 1 to specifically say what they are uncertain about, hopefully with some context relevant to the article. Pass 2 currently lets me see "uncertain" in the coder line, but without further information. It would be nice to have a few comments linked to this flag so the article can be sorted more quickly (ie. without having to read the whole article in every instance of uncertainty).

**Comment by davidskalinder** [comment]
Yeah, my hope is that this is a sensible compromise between a field that says "something about this event is uncertain" and having a zillion extra uncertainty fields.

So I'll put this in.  It occurs to me that once I do we can test how well it works in the UI, but the real test will come when we start doing pass 2 on data collected with this feature.  Which... unfortunately probably won't happen until we've already collected a bunch of pass 1 data with it.  Not sure I see a way around that, although hopefully we can set things up in pass 2 so that we can change it later if we need without too much trouble...

**Comment by davidskalinder** [comment]
Implemented in branch event_code_group_uncertainty.

**Comment by davidskalinder** [comment]
Now merged into testing branch.  This fix was made on top of upstream_development and so conflicted with more recent changes in split_location and (I think) drop_preset_tab, so there were some branch conflicts.  They seemed easy to resolve though?  Hopefully even to people who don't have the code memorized already lol?  Anyway, conflict resolved in testing branch.

**Comment by davidskalinder** [comment]
@olderwoman and @matthewsmorgan, this should now be live in the testing deployment, so please let me know if you think there should be any further changes!

**Comment by davidskalinder** [comment]
Note to self: before we go live, should probably change the variable names here to refer to the content of the questions rather than the structure (in case we move questions around...)

**Comment by davidskalinder** [comment]
> Note to self: before we go live, should probably change the variable names here to refer to the content of the questions rather than the structure (in case we move questions around...)

On second thought, I disagree with this.  Coders should specify which field needs review anyway, and we don't want to have to remember to keep the name of the review field in sync with the content.  Changes in tabs should be rare enough that we can keep it in sync with that.

So: I'm moving this back to the user testing column for now.

**Comment by matthewsmorgan** [comment]
Seems to be working. Looks good.

**Comment by davidskalinder** [comment]
@olderwoman sez:

> The BIG question for David is that we may need to have an “uncertain if Black” or “uncertain if protest” yes/no buttons to help coach people along in coding.

I've now added a "Which if any of the above items needs special review?" field to the article block, in branch article_uncertainty.  I'll wait to merge it in (to article_block_changes and then to testing) until I get confirmation that this does indeed address the problem she sensibly raises.

NB that this feature should be tested with considerable suspicion because I haven't had time to carefully make sure that I did indeed enable text inputs like this back when I created the article block.  It seems to be working in the dev deployment, but, yeah, we should remember to test with caution . . .

**Comment by davidskalinder** [comment]
@olderwoman sez:

> It’s more like the students are not coding borderline cases and we are getting no information at all from them, when we should be getting information so we can decide later about the events.

Well, so I guess the question is whether collecting information about uncertainty at the article level would hurt anything?  It seems to me that I probably should have put this field in in the first place (article description and screen-outs are now the only fields for which there's no way for coders to indicate uncertainty)...

@olderwoman / @matthewsmorgan, I think I'm going to merge this into the training version now and then either of you can tell me to take it out later if you don't like it?

**Comment by olderwoman** [comment]
I think there may be room on the screen one more article-level box spaced separately from the “not coded” boxes:
Uncertain about Black protests (code & explain)  And then instructions about using the uncertain box below & the event description box to explain uncertainty.

**Comment by davidskalinder** [comment]
> I think there may be room on the screen one more article-level box spaced separately from the “not coded” boxes:
Uncertain about Black protests (code & explain)  And then instructions about using the uncertain box below & the event description box to explain uncertainty.

So, wouldn't the same problem arise if they were unsure about any of the other screen-outs (viz., no protests, nothing post-1990, or nothing in US)?  It seems like any time they're unsure about any of those we'd want them to tell us that they're unsure and then code any possible events anyway?

If that's the case, then it seems like we should just change the text to something like "Which if any of the above items needs special review? Please code any events in doubt."?  (I think specifying another instruction about the event description box makes the instruction too long?)

**Comment by davidskalinder** [comment]
I've tweaked this wording slightly for clarity (it now reads "Which if any of the above items needs special review? Please add and code below any events in doubt.") and merged it into the testing branch and made it live on the testing implementation so you can see what it looks like on the form.  If it's bad for some reason, let me know and I can remove or change it?
