### ISSUE TITLE
Date format instructions for coder

### ISSUE THREAD

**Issue by matthewsmorgan** [davidskalinder/mpeds-coder#18]
I noticed some issues with dates being entered correctly while doing Pass 2, and now realize it's because there are no instructions for entering the date on Pass 1. It looks like the format the calendar tool uses is (Year/Month/Day). Can you please add that in parentheses after start date/end date?

**Comment by davidskalinder** [comment]
Hmm, when I enter a date in the UI in the wrong format, the UI attempts to format it correctly (and sometimes fails).  Also, in the UI it looks to me like the format is yyyy-mm-dd?  Let me know if that's not what you've seen in pass 2; maybe @alexhanna changed the format after that batch of data was collected.

Anyway, this is a good and nearly costless suggestion, so I'll definitely add it.  Do you think text like "Start date (yyyy-mm-dd)" is clear to, you know, normal people?

**Comment by matthewsmorgan** [comment]
Yes, I think that would be clear.

**Comment by davidskalinder** [comment]
Rad, thanks.  I'll probably roll this in with some other features since I assume you won't want to spend too much time testing this particular one :) ...

**Comment by davidskalinder** [comment]
It's probably overkill to put this in a whole separate branch, but anything worth doing is worth overdoing I suppose...  So, changed in change_date_instruction and merged into branch testing; the change should also be in the testing deployment.

**Comment by matthewsmorgan** [comment]
Yes, this change looks good on my end.
