### ISSUE TITLE
Aggregate event radio button + multiple & location unspecified buttons

### ISSUE THREAD

**Issue by olderwoman** [davidskalinder/mpeds-coder#19]
In planning pass 2 and pass 2.5 coding, realizing that it would help to have pass 1 coders able to flag "aggregate event" similarly to now flagging multi-day event.  This would be for either references to past events on multiple days (and would also involving clicking the multi-day event button) or to events in multiple unspecified places (e.g. "protests in 20 cities") which would be associated with a new button next to the location field for "multiple locations" and another for "no specific location" (e.g. boycotts, petitions, web mobilizations). @davidskalinder  @matthewsmorgan

**Comment by davidskalinder** [comment]
Relevant meeting notes:

Aggregate events:
  - Way to deal with things like multi-site events or events without specific info on location
    - Also with days
    - Also subparts of larger events
  - Some of this can be deferred to pass 2.5 (as it’s now called)
  - Also would be good to capture this at pass 1
    - MM worries (DS concurs) that coders might just mark many events as one aggregate event
  - This should only apply when the distinction is unknown
    - E.g., “Chicago, NY, and six other cities” should get three events: one in Chicago, one in NY, on aggregate
    - So maybe a way to mark when an event happens in an unknown number of places or at an unknown number of days
  - But we shouldn’t make coders code 50 events for “all 50 states”
    - And what to do about “several events across Harlem last night”?
      - CL: in pass 1, this is multi-location
      - Capturing location text might help resolve this eventually
  - To cut Gordian knot: pick one or two possibilities and try coding with it

**Comment by olderwoman** [comment]
Agree that these are the relevant notes.

**Comment by davidskalinder** [comment]
So I'm thinking that the best way to implement this will be a checkbox right after the event description field that says "Multiple indistinguishable events", a checkbox under the date fields that says "Date unspecified", and another under the location fields that says "Location unspecified".  I think that will cover all the cases?  But please somebody give a shout if that sounds wrong...

**Comment by olderwoman** [comment]
Sounds good to me for now. Can’t promise it won’t break in actual usage.

**Comment by davidskalinder** [comment]
So I just realized that we already have something very similar to "Multiple indistinguishable events" in the Yes/No tab:

> MULTIPLE EVENTS (The "event" is a reference to multiple events e.g. "protests last month" or "protests in 10 cities")

I think we should probably just keep that one where it is rather than move it to the (increasingly crowded) basic info tab (or keeping both, which I think is redundant)?

**Comment by davidskalinder** [comment]
Date unspecified fields (for both dates) and location unspecified fields added in branch basic_info_unspecifed and merged into event_item_changes and testing branches.

For some reason, this is working in all branches except testing (where nothing's going into the DB).  So the testing deployment might be broken for a few minutes...

**Comment by davidskalinder** [comment]
Okay, checkboxes are fixed in the testing deployment, so this issue is as fixed as I can manage for now.  In summary, I've added date and location unspecified fields and left the multiple events item in the yes/no tab as it was previously.

@olderwoman / @matthewsmorgan, I'll mark this for user testing -- let me know what you think of these changes?

**Comment by matthewsmorgan** [comment]
Just tried it out. This seems fine to me. It makes the Basic Info tab quite long, but it seems like scrolling is working well with this, I haven't had any trouble.

**Comment by matthewsmorgan** [comment]
Confirming that this works for me.

**Comment by olderwoman** [comment]
Interface has a no location button but NOT a "multiple location" button. There ARE both "no specific state/terr" and "multiple state/terr" options in the dropdown so this is probably ok.

**Comment by davidskalinder** [comment]
> Interface has a no location button but NOT a "multiple location" button. There ARE both "no specific state/terr" and "multiple state/terr" options in the dropdown so this is probably ok.

I think the discussion upthread got us to the point where we thought it'd be unnecessary?  This seems to be the comment where I started thinking this way: https://github.com/davidskalinder/mpeds-coder/issues/19#issuecomment-577376981

I think I agree with my past self that the "Multiple events" yes-no field makes a multiple-location field redundant?  Coders can specify events in multiple states with the drop-down and if necessary write in something like "Many unspecified cities" in the City/Town field?

**Comment by olderwoman** [comment]
agree
