### ISSUE TITLE
Give coders a way to mark clear repeats

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#20]
From meeting notes:

  - Way to flag that this is getting repetitive
    - I.e., “I’ve seen this at least twice before”
      - Otherwise sanity is threatened
        - Especially with pieces replicated over newswire
    - Flag can identify that article needs further attention by someone who can see all articles at once

**Comment by davidskalinder** [comment]
Mentioning @olderwoman and @matthewsmorgan here so they can find it and add if they want...

**Comment by davidskalinder** [comment]
Okay, @olderwoman and @matthewsmorgan, a question for you two on this one.  Is the idea here to give coders a way to mark articles that are very similar to those they've seen before, or events very similar to those they've seen before?  That is, should I put a checkbox for this in the article section, the event section, or both?

**Comment by olderwoman** [comment]
Let’s say event. Coder instructions will be to check this box if you know you have marked text for this event before and don’t want to keep repeating the same work. Mark text that seems like new information and be sure to check to see if there are new events you have not coded before that might be mentioned later in the article.

**Comment by davidskalinder** [comment]
Okay; but doesn't that mean that they'll still have to create every event in the article again in order to mark that they've seen it before?  Or maybe that's acceptable as long as they don't have to fill in all the other details huh...

**Comment by davidskalinder** [comment]
Note to self: This is implemented in branch mark_repeat_events, but these merge conflicts are becoming a mindfsck.  Better solution is to create a single branch for all the text changes, merge everything so far into that, and build any new text changes on top of that branch.  So far, new branch has been created and add_date_checkboxes has been merged in.

**Comment by olderwoman** [comment]
Yes, that is my thought. We will need to see how it goes.

**Comment by davidskalinder** [comment]
Merged into event_item_changes and that's merged into testing.

@olderwoman and @matthewsmorgan, this should now be live in the testing deployment (at the bottom of the basic info tab).

**Comment by matthewsmorgan** [comment]
This is working for me.
