### ISSUE TITLE
Handle ongoing and estimated events

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#31]
@olderwoman sez:

> Need some way to flag a multi-date event still ongoing (so you don’t have an estimated end date)

My questions: Wouldn't the end date be the same as the article date (since the article only refers to the stuff that's already happened)?  And maybe if it's ongoing then the "future event" box should also get checked?

**Comment by davidskalinder** [comment]
Maybe the best way to handle this is to simply add an "event ongoing" checkbox to the yes/no list?  Or if we don't care about distinguishing between them, to change the "Future event" box to something like "Future or ongoing event"?

**Comment by olderwoman** [comment]
Possibly. It just seems conceptually easier as a coder to mark estimated date or event continuing right next to the date boxes. I gather that is not easy to program?

**Comment by davidskalinder** [comment]
I didn't mention @matthewsmorgan on this before so I'll do so now to see if she has opinions on this...

Anyway, nah, it won't be too hard to implement.  I guess I'm more nervous about cluttering up the interface.

I suppose that the checkbox about "Future event" should go in the same place as a new checkbox about "Event continuing"?  So if we put one by the dates then we should put both there?

Also, do you think issue #11 will be enough to capture what we need for "estimated date"?  Or do we definitely want an additional checkbox for that as well?

**Comment by olderwoman** [comment]
I’m inclined to feel that estimated date is a big deal but the check box could just be “est” or “Est Date”. This is relevant when trying to match events up in pass 2. We can/should also train coders to mark phrases like “protests last month” in the time/duration text field.

**Comment by olderwoman** [comment]
Deciding how to code ongoing events is difficult but I don’t like the solution of ‘ending’ on the publication date.

**Comment by davidskalinder** [comment]
Changed in branch add_date_checkboxes.  Merged into testing branch with conflicts because of new location fields. Got a strange permissions error after fixing the conflicts, solved by re-chown-ing the entire directory.  Deployed in testing.

**Comment by davidskalinder** [comment]
So, @olderwoman and @matthewsmorgan, I put in what I think is the most sensible formatting for this and it should now be visible on the testing server.  Let me know if you think it needs anything else!

**Comment by davidskalinder** [comment]
So I just realized reading @matthewsmorgan's codebook that there might be a separate need for "Date estimated" checkboxes as well as for the future event and event ongoing checkboxes?  If so then I think what makes the most sense is to put a "Date estimated" checkbox immediately after both the start date and after the end date fields (and so above the future and ongoing checkboxes)?  Or is this overkill and should be handled by the existing checkboxes as well as the special review field?

**Comment by olderwoman** [comment]
It is often the case in reading a particular article that you cannot identify the start date of an event. As I’ve said before, ongoing event is conceptually somewhat different from multi-date event in the past where you don’t know exact start or end dates, you are just estimating from ambiguous text. I should talk over with Morgan about how to handle this. Or suggest that David try coding some articles to see what it feels like in practice.

**Comment by davidskalinder** [comment]
Yeah, I think the issue of estimated dates is quite different from the issue of ongoing events.  I think I'm running out of ideas about why not to put these checkboxes in?...

**Comment by davidskalinder** [comment]
Okay, I've put in checkboxes for approximate dates for now (in branch dates_estimated, and merged into event_item_changes and testing branches).  Should be working in the testing deployment, so I'll mark it for user testing for now.  But @olderwoman and @matthewsmorgan, if you prefer that we do something different here please let me know...

**Comment by matthewsmorgan** [comment]
This seems to be working for me. To be clear, one should mark "Start date unspecified" if there is absolutely no information (e.g., march occurred last month) indicating a date? Is that correct & how one should distinguish from "Start date estimated"? Assuming these might be both selected for many cases, but want to be clear on the distinction.

**Comment by davidskalinder** [comment]
Mentioning @olderwoman since I think this will require her attention . . .

So the "date unspecified" fields were discussed in slightly more detail in issue #19--it looks like that was my attempt to make concrete our discussions about article text like "following other recent protests" . . .

I think my notion is that "unspecified" and "estimated" dates should (almost always) be mutually exclusive?  Since if I can estimate it, then it must have been at least vaguely specified?  But the fact that your notion is different is probably an indication that something isn't clear enough.  Perhaps the question is what precisely we want these fields to capture/distinguish?

**Comment by olderwoman** [comment]
My review is that date unspecified and date estimated DO overlap.  The latter being “unspecified and I have no clue” and  the latter being “unspecified but there are some clues”.  One could argue that the same effect could be accomplished by having one button for “date unspecified or unclear”  AND and instruction to give an estimated date if possible.

**Comment by davidskalinder** [comment]
> My review is that date unspecified and date estimated DO overlap. The latter being “unspecified and I have no clue” and the latter being “unspecified but there are some clues”. One could argue that the same effect could be accomplished by having one button for “date unspecified or unclear” AND and instruction to give an estimated date if possible.

Hah, okay.  So it does seem like leaving both buttons will work whether they're exclusive or overlapping, but combining them into one will only work if they overlap (or if we don't care about the distinction)?  And I think the (only?) downside of leaving both buttons is that it takes up two extra lines of space (unless having both is confusing enough to lead coders to do something wrong with these or other fields).

The space is not a negligible issue considering how long the basic info tab is getting, but on the whole I'm inclined to err on the side of leaving them both in and getting redundant info?  We can always combine them later, but splitting them later will require someone to decide how to split each case...

@olderwoman / @matthewsmorgan, how does that strike you?  Am I overlooking a more serious cost of leaving it as it is?

**Comment by olderwoman** [comment]
In practice, I see no downside to combining estimated and unspecified, and training coders that they should try to estimate dates and mark text in the “time” field for whatever clues there are. Sometimes all you know is “last year” or “last month” or occasionally “in the past.” It would actually help if the date field could take only a year or only a year and month, so as to avoid false precision when you don’t have it. But I think the date field has a restricted format, which is necessary for the calendar to work (and I REALLY LIKE) the calendar. We should decide whether pass 2 coding is best facilitated by leaving the date blank when we  don’t know the date, and using the text box instead, or best facilitated with an estimated date even if it is wrong.

**Comment by davidskalinder** [comment]
> In practice, I see no downside to combining estimated and unspecified, and training coders that they should try to estimate dates and mark text in the “time” field for whatever clues there are. Sometimes all you know is “last year” or “last month” or occasionally “in the past.”

Okay, so wouldn't those be cases (especially the last one) where we'd want the coder to check the "unspecified" box but not the "estimated" box?  Or maybe we want them to go ahead and estimate a date in every single case?

> We should decide whether pass 2 coding is best facilitated by leaving the date blank when we don’t know the date, and using the text box instead, or best facilitated with an estimated date even if it is wrong.

I think this is the key.  If we always want them to estimate the date, then the "unspecified" field becomes irrelevant and we can cut it.  If we at least sometimes want them to tell us that there wasn't enough info to make a sensible estimate, then I think we want to keep the "unspecified" field.

> It would actually help if the date field could take only a year or only a year and month, so as to avoid false precision when you don’t have it. But I think the date field has a restricted format, which is necessary for the calendar to work (and I REALLY LIKE) the calendar.

So yeah I see what you mean here.  A proper solution I think could be to split the year, month, and day fields so that coders can fill in whichever they can.  (I don't think we want to mix dates at different grains, which can cause strange problems when doing even simple things like sorting.)  But I'm not sure that the value is worth the extra complexity?  Especially with an "estimated" checkbox (and since what is being estimated is always in fact one day and not a multi-day period).  Does having overly-specific dates hurt us in pass 2 if we know that they're estimated?  (Of course we could always implement separate year, month, and day fields in pass 2 even if it's not in pass 1.)

**Comment by olderwoman** [comment]
ANSWERING THIS:So yeah I see what you mean here. A proper solution I think could be to split the year, month, and day fields so that coders can fill in whichever they can. (I don't think we want to mix dates at different grains, which can cause strange problems when doing even simple things like sorting.) But I'm not sure that the value is worth the extra complexity? Especially with an "estimated" checkbox (and since what is being estimated is always in fact one day and not a multi-day period). Does having overly-specific dates hurt us in pass 2 if we know that they're estimated? (Of course we could always implement separate year, month, and day fields in pass 2 even if it's not in pass 1.)

MY ANSWER: Sometimes you can be confused in realizing two events are actually the same event if the estimated date is too far off, but this also happens when the coder has just made a mistake about the date. I’m thinking that having them guess if they have partial information  and leave it blank if not and check estimated or unspecified should give us what we need to know in pass 2.  We should get Morgan’s opinion on this specific issue.

**Comment by davidskalinder** [comment]
> Sometimes you can be confused in realizing two events are actually the same event if the estimated date is too far off, but this also happens when the coder has just made a mistake about the date. I’m thinking that having them guess if they have partial information  and leave it blank if not and check estimated or unspecified should give us what we need to know in pass 2.  We should get Morgan’s opinion on this specific issue.

Okay, I'll stand by for @matthewsmorgan to weigh in.  To clarify, I think what we need to know here is:

1. Do we lose any valuable information by combining the date unspecified and date estimated fields, and
1. Do we gain very much by splitting the date field into year, month, and date fields (effectively, to allow NA values in some but not others)

The two things I'll note about the second item are a) it might be relatively difficult to implement, so I'm not 100% sure I can deliver it by the time we want the army to start on the production version; and b) it will take up more space than the current version since there will be three fields per date rather than one.

**Comment by matthewsmorgan** [comment]
Answering this via email since I'm on my phone, hoping it works. I think 1)
it makes sense to combine the fields and have the coders at least provide
an estimated date in all cases. Some info (even if date of publication) is
better than nothing, and the estimated/unspecified fields can basically
work as a flash for pass 2. And 2) this sounds tedious, and probably more
work than value

**Comment by davidskalinder** [comment]
Okay makes sense to me.  Seems like if we want them to estimate a date every time then the prompts should just read "date estimated"?  That is, I'll just cut the "date unspecified" fields?

I'll implement that shortly, but if that's wrong then let me know and I can correct it before it gets merged into the testing/production versions.

**Comment by olderwoman** [comment]
I think that is right.

**Comment by davidskalinder** [comment]
This should be changed now, in branches basic_info_unspecified, event_item_changes, and testing, and in the testing implementation.

@matthewsmorgan and @olderwoman, you should probably give this a look to make sure it's how we want it and that it hasn't broken anything new...

**Comment by olderwoman** [comment]
Interface as it exists today 2/13/20 looks good to me on this point. I would define this as closed.  I am not sure how to test whether it breaks anything but I did successfully mark an event as ongoing. I also successfully created a fake event that is both future and ongoing and it accepted my clicks.

**Comment by davidskalinder** [comment]
@olderwoman sez (with @matthewsmorgan CC'd):

>Uh oh, last minute confusion. A student is confused by “article describes future event” and “article describes ongoing event”. The correct labels would be “this is a future event” and “this is an ongoing event” or even “future event” and “ongoing event” . Reason: the article describes ongoing Wisconsin protests but the NAACP statement is a one time thing. Or if fixing this is too much of a pain, we can just do this with training.

So this shouldn't be too hard to fix, and worth doing I think.  However the reason I phrased it this way was to make clear that these events are in the future or ongoing from the point of view of the article (rather than some other POV, most notably the coder's in 2020 but possibly some other crazy thing).

So I guess my suggestion would be "Article describes this as a future event" and "Article describes this as an ongoing event"?  Wordier obviously, but maybe worth it if the meaning is clearer?

**Comment by olderwoman** [comment]
I am ok with your wording if it fits, agree it is the clearest way to say it

**Comment by davidskalinder** [comment]
New wording fixed in branch event_item_changes and merged into testing and master.

@olderwoman / @matthewsmorgan, this should now be live in both the testing and the production deployments, so have a look if you're inclined; otherwise I'll probably close this issue next week with the rest of the stuff in user-testing.
