### ISSUE TITLE
Add date to the article metadata table

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#39]
So I think this is the proper place for this in MAI.  It kinda kicks down the road the issue of how to get the dates... but this is the way it currently works for article title as well, which has the same issue.  Maybe someday MAI can get dates direct from SOLR...  But for the short- and medium-term at least, I think just adding the field to the metadata table is the best solution...

**Comment by davidskalinder** [comment]
Should be fixed in branch enable_article_dates.  However, the new column is only added on table creation, meaning that for existing databases it has to be added manually with `ALTER TABLE article_metadata ADD COLUMN pub_date DATE;`.

@alexhanna, do you know of some better trick for handling small changes like this to tables?  I guess this is technically a database migration, but it seems silly to bring in a whole set of migration tools for tiny changes like this (or for the table constraints that will be added in other issues)...

**Comment by davidskalinder** [comment]
Merged into testing and live at testing deployment (with ALTER TABLE done in testing DB).  This change should be invisible, so I'm moving the issue to done for now; shouldn't close it until dependencies have been user-tested though.

NB1: Will need to remember to alter the table in the production version when it gets this code.  Ugh.
NB2: Don't use RENAME TABLE to migrate: this will change other tables' foreign keys!

**Comment by alexhanna** [comment]
I've used [alembic](https://alembic.sqlalchemy.org/en/latest/) in the past. It does seem like overkill but I don't know of a better migration strategy.

**Comment by davidskalinder** [comment]
Uf.  Yep, that seems pretty heavy all right.  And would that even solve the problem of keeping DB changes in sync with code changes?

 I'm not sure what else to do aside from remembering to alter tables whenever the branches that change them are merged in?  Have you done stuff like this in the past?  Or have your tables been so robust that they never changed? :)

**Comment by alexhanna** [comment]
I don't know if "robust" is the word I'd use but yeah I haven't changed them much.

**Comment by davidskalinder** [comment]
Got around having to ALTER TABLE in production deployment by simply zorching the production DB and installing from scratch in order to set up the live launch.  Should all be working now.

**Comment by davidskalinder** [comment]
Sigh apparently this got like [PR'd](https://github.com/MPEDS/mpeds-coder/pull/18/commits) and then un-PR'd and then merged and unmerged and FSM knows what.

So since @alexhanna will actually be needing this soon as part of #59, and since functionality for `addArticles()` to load the dates from a file has been moved to #112, I think I'm simply going to reimplement this in a new branch that can be part of what will soon get PR'd upstream once and for all...

**Comment by davidskalinder** [comment]
Should be reimplemented at a0078a1e8872.  This will fold into and be tested with #113.

**Comment by davidskalinder** [comment]
Superseded by #113.  Closing.
