### ISSUE TITLE
Pull articles from old production deployment into new one

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#40]
Even though this is deployment-specific rather than about MAI code, it's too easy to lose track of the issue in emails, so I'm putting the info here.

From my email of 2020-02-05:

>I think I've got things set up to load articles into the production DB, but I just wanted to double-check that how I'm about to do it is how we really want it.  The articles I've selected from the old DB (the one at the blacknews URL) are all the ones for which there are no non-blank codes.  (This might include some articles that once had information in a field that someone later cleared.)  Out of the 7,910 articles in the blacknews database, 6,452 are now uncoded by this criterion, whereas 1,458 have been coded.

> One thing I wanted to check in particular is that the articles I'm considering coded are all articles that have any annotations from any coder, including, for example, the articles that Morgan, Chaeyoon, and I used to get familiar with the coding process a few months ago.  If when considering which articles to pull I should instead ignore the articles that we three or any other users coded, or if there's any other restrictions I should make, please let me know now!  Changes down the road should be doable in theory, but increasingly delicate as we start to collect real data.

Follow-up: DS and MM's test coding should be good enough.

From team meeting 2020-02-10:

> Need to treat Chaeyoon’s article as not coded, coder1p_1 as real coding; look at pamela2’s articles to confirm sensibility

All other users look like real people.  Given that the only thing that needs special handling is CL's single article, my inclination is to simply erase all coded material in that article in the original data and leave the query as is...

I'm mentioning @olderwoman here to give her a chance to object, but otherwise I'll go ahead with this plan.

**Comment by olderwoman** [comment]
You should check but I’m 95% sure that Pamela2 is real coding.

**Comment by davidskalinder** [comment]
Ah, yes, sorry, I did confirm that Pamela2's coding looks real.  So yeah, just the one bad one from Chaeyoon, which I think I should simply clear.

**Comment by davidskalinder** [comment]
Cleared CL's article from old DB.

**Comment by davidskalinder** [comment]
Pulling is now implemented by an SQL file that can be run with `sudo cat /var/lib/mysql-files/get_uncoded_blacknews_articles.sql | mysql -u mpeds`.  This file is not under version control since it's specific to the deployments.  The output can be opened with vim and manipulated to get a date column with `%s/.\{-}_\(.\{-}\)_.*/&,\1/g` (NB: air code).  It can then be moved somewhere where setup.py can get at it as usual.

**Comment by davidskalinder** [comment]
Done: 6453 articles exported and imported.
