### ISSUE TITLE
Put SOLR ID into coder table export

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#43]
Wherever the query is that exports the coder table file, it should have SOLR ID in it, for now at least.

**Comment by davidskalinder** [comment]
Looping @johnklemke in here...

**Comment by johnklemke** [comment]
We do have the SOLR_ID in the coder table file Pam generated on Monday. There's also some article metadata that will need to go into the articles table but not the coder lines table. Doesn't hurt to have this in coder table files, though -- if we come up wiat a way that gets us the full article text and the metadata as well for loading into the article table, i'll just ignore it in coder tables.

**Comment by davidskalinder** [comment]
Ah, I see: it's the stuff associated with the SOLR ID we need, not the SOLR ID / MAI ID pairs.  In that case, I think #45 is the real issue here, so I'm going to close this issue and ask you a question in that one. :)
