### ISSUE TITLE
Fix sucky delimiters in coder table export

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#46]
The test for this is whether MS Access's text import digests it easily.  Be sure to check for unmatched quotation marks, which are rare but srsly annoying.

@olderwoman and @johnklemke, mentioning y'all here so that you'll get notifications about this issue.

**Comment by johnklemke** [comment]
Okay -- I dug some more into this when I realized Excel actually does better with a comma-delimited coder table than Access was. In the Access external data import wizard, I stumbled on the Text Qualifier specification, which defaults to None but can be set to double quotes. Flipping it to double quotes produced an Access table that's much more sensible. So, I think this can be closed.

**Comment by davidskalinder** [comment]
Ah, great!  Does it even handle unmatched quotes?

I know Access's text import is quite flexible, although it may take a lot of mouse-clicks to get all the options right.  Which might be good enough for this relatively rare task...

**Comment by johnklemke** [comment]
I think the jury's still out on that question, but it looks promising.

**Comment by davidskalinder** [comment]
Okay, sounds good.  I'll close this, but feel free to re-open this one or to open a new issue if it goes wrong again and needs a fix on the MAI side.
