### ISSUE TITLE
Collect reason why no events are coded

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#5]
To do this properly, need to record at least the reason and probably also a check-box for no event being coded.  This should be done at the article level, and therefore should be handled as in #4.

This time the human-kludge option is to edit "Provide a short description of this event" to "Provide a short description of this event or explain why no event coded".

**Comment by davidskalinder** [comment]
Somewhere (UI notes suggest the yes/no tab?), want:
- Codable events (per article)
  - No codable events  (give brief explanation in event box)
  - One codable event
  - More than one codable event

...in addition to the reason.

I'd suggest that this goes wherever other article-level stuff goes (which it's increasingly clear that we'll need to build properly).

**Comment by olderwoman** [comment]
This is a test comment

**Comment by davidskalinder** [comment]
From meeting discussion:

Article-level checkboxes:

  -  No protests
  -  Protests but no black protests
  -  No events in the US
  -  No events after 1990

**Comment by olderwoman** [comment]
good

**Comment by davidskalinder** [comment]
Fixed in branch change_article_textboxes.

**Comment by davidskalinder** [comment]
Ah, I just merged this into the testing deployment but forgot that it requires a change to the database, so the testing deployment will be broken for a few minutes while I fix it, sorry!

**Comment by davidskalinder** [comment]
Okay, should now be working in testing.  So @olderwoman and @matthewsmorgan, please see if you can break it!  And let me know anything that needs changing.

Woo hoo!  Article-level coding, baby!  Correct data granularity is such a thrill.

**Comment by matthewsmorgan** [comment]
Seems to be working.
