### ISSUE TITLE
Better solve scrolling of data entry panel

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#51]
The trade-off of allowing the coding panel to scroll along with the article is that for long articles, scrolling now moves with the articles, so coding text at the bottom of the article requires scrolling all the way back up to the controls again.

Possible solutions for the future would be to make the article-level screenouts (and maybe other batteries too) fold to take up less room and make the scrolling sticky like it was before; or, ideally, to have separate scroll bars for the article text and the controls.

_Originally posted by @davidskalinder in https://github.com/davidskalinder/mpeds-coder/issues/25#issuecomment-575843803_

**Comment by davidskalinder** [comment]
@matthewsmorgan reports that not having this in place makes coding long articles extremely annoying, slow, and error-prone, so I'm going to make this one of the highest-priority of the non-showstopping issues.

Also mentioning @alexhanna since we've discussed possible solutions in the past.

**Comment by davidskalinder** [comment]
Hey how about that there's a [CSS `overflow` property](https://www.w3schools.com/css/css_overflow.asp) with an `auto` options that adds scrollbars if the element's content is too big and also [a `vh` size setting](https://www.geeksforgeeks.org/how-to-give-a-div-tag-100-height-of-the-browser-window-using-css/) to set things to the viewport height!  It's almost like someone had solved problems of designing web pages before...

Anyway, now need to figure out roughly how much of the vh we actually need since there's a header and a footer...

**Comment by davidskalinder** [comment]
> Anyway, now need to figure out roughly how much of the vh we actually need since there's a header and a footer...

Grunt.  Looks like Flask sets the header size dynamically:

https://github.com/davidskalinder/mpeds-coder/blob/c9292d6501211fec855d00107b24be166ed9b3bc/static/bower_components/bootstrap/less/navbar.less#L13

...and doesn't set the footer size at all.

So the best way to set the coding panel size might well be to guess (like, oh, 90%?)... but I suppose it's worth checking first to see whether there's some clever Flask Way of doing this kind of thing...

**Comment by davidskalinder** [comment]
Wayll, I can't find where `@navbar-height` is set.  (All that grep turns up in the whole project root is Bootstrap CSS files that define things with it.)

But however it's set, the way it ends up in my FF windows is 50px for the nav bar plus 4px for each border and 20px for the bottom margin; so I guess conservatively it's pretty unlikely that that thing will end up being more than 100px tall without some pretty severe changes?

As for the footer, here's the only styling info I can find:

https://github.com/davidskalinder/mpeds-coder/blob/c9292d6501211fec855d00107b24be166ed9b3bc/static/style.css#L360-L365

So I guess again we could be conservative and leave about 100px for the footer total height?

So that leaves the plan at making the data entry panel the height of the viewport minus 200px, with automatic scrollbars, and sticky so that it always stays in the window.

**Comment by davidskalinder** [comment]
> So that leaves the plan at making the data entry panel the height of the viewport minus 200px

Looks like 120px is a good number actually: enough to guarantee it doesn't expect to use the header's space and enough to not expect the footer's either.

Now I just need to figure out why the CSS sticky positioning isn't working and whether it's for the same reason that @alexhanna originally wrote a JS function to set sticky functionality that should usually be controllable by CSS alone...

**Comment by davidskalinder** [comment]
Resources on stickiness:

https://www.w3schools.com/css/css_positioning.asp
https://stackoverflow.com/questions/43707076/position-sticky-not-working-css-and-html
https://blog.cloud66.com/position-sticky-problem/

No parents have `overflow` set that I can see, so I still don't know why this isn't working...

**Comment by davidskalinder** [comment]
Well, for the life of me I can't get the `position: sticky;` CSS working and for the life of me I can't figure out why.  So I'm going to reenable the old JS that seems to do the same thing.  It sounds like it's moderately better-supported anyway and comes with a performance hit that should be pretty minimal in our case.

**Comment by davidskalinder** [comment]
> Looks like 120px is a good number actually: enough to guarantee it doesn't expect to use the header's space and enough to not expect the footer's either.

I continue to tweak this (down to 80px, now).  It seems to still prevent weird overlaps with the footer, but I confess I'm not 100% sure it won't do something strange if there's an extremely short article someday (which I can't find and can't create since they're still in SOLR).  But I think that'd be pretty unusual and also would probably fail fairly gracefully anyway, so I'm going to leave good enough alone.

Also: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects .  So the CSS would deffo be better if we got it working, but... well enough alone.

**Comment by davidskalinder** [comment]
Fixed in branch ending at [001b2cf](https://github.com/davidskalinder/mpeds-coder/commit/001b2cf9336ad7f8bd9b1a1bb4c80b6e0c8858b8). Merged into `testing` and `master` (with some easily-resolved conflicts). Deployed into testing UI.

**Comment by davidskalinder** [comment]
Okay, this one is in the testing deployment and ready for the UI testing team to have a look: @olderwoman, @matthewsmorgan, and our newly-minted MAI UI expert @limchaeyoon!

Separate scrollbars should now appear for the block of coding controls and for the event descriptions when there are enough of them, and they should stay fixed when the article is scrolled.  This should let you keep the controls on the screen when coding the bottom of long articles.

I think everything is working, but these style changes can be finicky, so please give them a look with suspicion.  Ideally, check how everything works with edge cases like especially long or short articles or different browser sizes.

As @matthewsmorgan mentioned last week, this will hopefully make coding long articles much less annoying, so if everything looks good to y'all as a collective then let me know and I'll make the change live in the production version ASAP.

**Comment by matthewsmorgan** [comment]
Tried this out. Wow, is this a game changer. So much easier to do the text
select now.

One bug that would be nice to fix: When you're going through the different
coding areas (e.g., Basic Info, Text Select), if you're at the bottom of
the article and switch to a different coding area (e.g., you just finished
doing something in Basic Info and switch to Text Select), it automatically
jumps the article back up to the top (so if you were looking at something
at the bottom of the article you're not anymore). Would be nice if
switching didn't cause this extra scrolling back to the bottom or wherever
the coder was working.

Once this is fixed and we implement, I think it would be nice to let the
coders know we've made this change (so they aren't caught off-guard, and so
they can let us know if they come across any further issues we don't notice
in testing for some reason). I think it's fine if this email comes from
you, David, since you'll roll it out and have done the work to fix it.

**Comment by davidskalinder** [comment]
> Tried this out. Wow, is this a game changer. So much easier to do the text select now.

Fab!

> One bug that would be nice to fix: When you're going through the different coding areas (e.g., Basic Info, Text Select), if you're at the bottom of the article and switch to a different coding area (e.g., you just finished doing something in Basic Info and switch to Text Select), it automatically jumps the article back up to the top (so if you were looking at something at the bottom of the article you're not anymore). Would be nice if switching didn't cause this extra scrolling back to the bottom or wherever the coder was working.

Hmm yeah I see what you mean, that would be a good change.  I don't think it's related to any of the control panel positioning or scrolling though, so I'll open a new issue for it and investigate.

It seems like this is minor enough that we should go ahead and deploy the changes to the control panel scrolling without waiting to fix these article jumps?

> Once this is fixed and we implement, I think it would be nice to let the coders know we've made this change (so they aren't caught off-guard, and so they can let us know if they come across any further issues we don't notice in testing for some reason). I think it's fine if this email comes from you, David, since you'll roll it out and have done the work to fix it.

Sounds good, I'll send them an email when I hit the Go button.

**Comment by davidskalinder** [comment]
Hey folks, just to give this one a nudge:

- Should I wait until @olderwoman and/or @limchaeyoon have had a look at this, or has @matthewsmorgan spoken for the collective?
- Should I fix the article-jumping behavior @matthewsmorgan described before deploying the scrollbar funcitonality?

If the answers are not to wait for either of these, then I'll go ahead and deploy and email...

**Comment by olderwoman** [comment]
Trust Morgan on this one.

**Comment by davidskalinder** [comment]
> Trust Morgan on this one.

Hah, sounds good.  That second point seems minor enough that I think I should go ahead and deploy this; if there are further comments on that issue they can go in #95.

**Comment by davidskalinder** [comment]
Deployed and emailed.  I'll close this, but if other stuff comes up we can reopen.
