### ISSUE TITLE
Fix bad formatting in coder-table export

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#63]
@olderwoman sez:

> So the latest round of processing, but not last week’s, is producing a crash. I had previously built in a variable to allow me to identify when/where the crash occurs, but it has been so long since the program crashed that I cannot remember how to use that information to diagnose the problem. In short, there will be a delay in generating the quality control spreadsheets. This bug is occurring in the “step 1” program that processes the coder table. As I said, it has to be a problem with the inputs somewhere in the newest data because (a) it worked just fine last week and (b) it is getting through most of the variables before it crashes.

> FYI the problem is an unmatched quote mark in the marked text for issue.  A brute force subinstr command in Stata isn’t working. I’m going to have to be more subtle about this. But it will happen again, so I need to figure out a more general solution.

@davidskalinder sez:

>Hmm okay.  I haven't touched the functionality of the coder-table export, so presumably this was a bug in previous versions also.  Could you send through the ID (MAI's or SOLR's) of the bad row so we can track it down?

**Comment by davidskalinder** [comment]
From @olderwoman:

> Id info: article_id=519, event_id=1740, coder_id=alana, id=27326, variable=issue-text, text starts with an unmatched quote

(This is in the bpp deployment.)

**Comment by davidskalinder** [comment]
So @olderwoman, having had a look at this, I'm not sure how much could be done in producing this file.  Here's the full raw text of the problematic row:

```
27326,519,1740,issue-text,7-43-170,"""If people lose their jobs because we are here fighting for equality, then the Whites and Cubans don't have any respect for us.",alana,2020-03-12 13:41:04,"Miami-Times;-Miami,-Fla.",1997-02-27,"Miami-Times;-Miami,-Fla._1997-02-27_b4f8975ecef275ceb0c2f14deb9f3cac"
```

That sixth column, which is enclosed in `"` characters, starts with `""`, which is a properly-escaped quote character in the way that Excel (at least) expects it.  It is unmatched, but since it's escaped correctly, it should be read as just a regular character within the text of the field.

So that's about the most we can do as far as the MAI exports are concerned.  Of course since there's no CSV standard, other programs might expect different escape characters, but at the moment I'm actually manually changing the article-level files so that they have the quotes-escaped-by-quotes, just like this file... so it seems like this should work as is?

It's hard to tell what a better solution would be without debugging your Stata scripts (which I think would take me quite a while); but I assume there's a way to tweak the options on the statement that imports the file?  Perhaps to expect a more Excel-like setting?

**Comment by davidskalinder** [comment]
BTW I have checked that that row opens correctly in Excel, though of course that doesn't necessarily mean that Stata will digest it properly...

**Comment by olderwoman** [comment]
Stata DID digest it properly through two steps. It is crunching at the step of concatenating multiple lines of marked text into one variable, which is done by using levelsof and putting the results into a local.

**Comment by olderwoman** [comment]
BTW dropping that unmatched quote created a new crash, which I’m still tracking down . . .

**Comment by davidskalinder** [comment]
> Stata DID digest it properly through two steps. It is crunching at the step of concatenating multiple lines of marked text into one variable, which is done by using levelsof and putting the results into a local.

Hmm, got it, sounds like it depends on the details of the way that code is storing that character then.  Let me know if you want me to dive into the Stata scripts, otherwise I'm afraid there's not much I can do (short of creating an entirely new export system, which is issue #58 but will be done rather later than today, heh)...

**Comment by olderwoman** [comment]
Not expecting you do to anything today. I’m going to need to step through the logic of this carefully anyway. There is another problem I know of that is waiting for me in the way I concatenate the marked text: at some point I will run into the maximum length of a local.

**Comment by davidskalinder** [comment]
Sounds like this got there eventually, notwithstanding some problems with backticks in addition to the stuff mentioned above.  Hopefully #58 will take care of all this stuff before too long.
