### ISSUE TITLE
Make it easy to find corresponding event- and article-level export files

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#66]
Since part of both #56 and #62 is making sure that it's easy to find the files created by runs of each process that (as much as possible) correspond with one another, I figured it was best to create a single issue for it here.

I've created `exports/old` within the testing deployment and done a run of both files for the testing deployment as I normally would every (other?) Monday morning; so now these two new files are the only ones in the root of the `exports` folder and all files from previous runs are in the `exports/old` folder.

@olderwoman, does this resolve the problem of getting the right pair of files for the Stata scripts?  I realize that there might be a further problem if you're copying the files into an input directory where the scripts need to find the files, but if that's the case then maybe you could similarly create an `old` subdirectory there and simply have Stata read the two files that are in the input directory's root?

Anyway, let me know what you think and if there's anything I can do on the server side to help.

**Comment by olderwoman** [comment]
So you will create both files? I see bpp_test_coder_article_annotation_2020-04-111929.csv and coder-table_2020-04-04_111916.csv
Are those the files I should see?

**Comment by davidskalinder** [comment]
> So you will create both files?

That's what I've been doing for the last few weeks (since the article-level file requires some hacking in the terminal); so yeah, I'll probably have to keep doing it for as long as we need these (quasi-)paired files?

> I see bpp_test_coder_article_annotation_2020-04-111929.csv and coder-table_2020-04-04_111916.csv Are those the files I should see?

Yeah, that looks ilke those are the right ones -- to be exact, it should be these two:

```
bpp_testing_coder_article_annotation_2020-04-04_111929.csv
coder-table_2020-04-04_111916.csv
```

Then next time I run it, I'll first move those two to the `old` subdirectory and leave the two new ones in the root of `exports`.  Note also that the article-level file begins with the name of the database, so that files from the production version will look like `bpp_coder_article_annotation_yyyy-mm-dd_hhmmss.csv`.

**Comment by olderwoman** [comment]
OK. Notice that minor inconsistencies in where there is a hyphen and where there is an underscore can generate problems for being able to process files in a consistent way using old code without having to change the code every time there is a new file. I’m trying to have the file parameters occur only once at the beginning of the program and get carried through the rest of the way.

**Comment by davidskalinder** [comment]
> OK. Notice that minor inconsistencies in where there is a hyphen and where there is an underscore can generate problems for being able to process files in a consistent way using old code without having to change the code every time there is a new file.

Agreed.  I'm trying to be consistent about using hyphens only to separate parts of dates in any new names.  I left the hyphen in `coder-table` because it always had one and I didn't want to screw up anything that depended on the old name (but I'll happily change it to `coder_table` if you prefer).

> I’m trying to have the file parameters occur only once at the beginning of the program and get carried through the rest of the way.

Sounds good -- so hopefully the current names and locations will work?  But otherwise let me know.  Maybe we should leave this issue open until we've produced another round of reports in order to make sure it all works?

**Comment by olderwoman** [comment]
The easiest way to process this from my point of view is to have a date that I pass to both the line to read the file and use in naming the output files form my run that will always have the same format for different uses. If the timestamps attached to the two files you create were exactly the same, I’d use that, but as the are not, I won’t. I will write file read commands that take the date and timestamps as parameters so it is important for me that the micro details in the file names are consistent except for the change in the date & time stamps, and that the date and time stamps always have the same format so I can just plug them in at the top of the run and be done with it, knowing everything else will propagate correctly. Note: I just realized that there is a way I can make this even more bullet proof than I have in the past, in terms of a way to solidly pass the parameters through the four programs that generate the tables we use for coder review.

**Comment by davidskalinder** [comment]
> The easiest way to process this from my point of view is to have a date that I pass to both the line to read the file and use in naming the output files form my run that will always have the same format for different uses. If the timestamps attached to the two files you create were exactly the same, I’d use that, but as the are not, I won’t.

Yeah, as I understand it you weren't just expecting the format to be the same -- you actually wanted the timestamps to be identical.  Like I said in umm one of the other threads, if it saves you a lot of trouble we could simply change one or both of the filenames so that they match?  That creates some hazards, but hopefully they will soon be made moot by me just outputting one file instead of two...

> I will write file read commands that take the date and timestamps as parameters so it is important for me that the micro details in the file names are consistent except for the change in the date & time stamps, and that the date and time stamps always have the same format so I can just plug them in at the top of the run and be done with it, knowing everything else will propagate correctly.

Okay, makes sense.  The formatting is as consistent as I know how to make it now, but if you let me know what you want the names to be I can change them however you want.

> Note: I just realized that there is a way I can make this even more bullet proof than I have in the past, in terms of a way to solidly pass the parameters through the four programs that generate the tables we use for coder review.

Bullets are surprisingly slippery things!  But yes, let me know if there's anything I can do to smooth the process (or we can talk it through on Monday).

**Comment by olderwoman** [comment]
I can work around the timestamps not being identical. I’ll just put the date in place and the timestamps in two other places.

**Comment by davidskalinder** [comment]
This process seems to have worked in both last week's test runs and this week's real runs, so I'm going to go ahead and close this issue; but of course anybody can feel free to reopen if any new problems emerge.
