### ISSUE TITLE
Create MAI database storage for text field

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#78]
To reiterate what I had iniitally put in #76: I need to look into how to get MySQL to handle large amounts of text elegantly.  Also, I suppose this should go into `article_metadata` even though it will make the table name at least partially false.

**Comment by davidskalinder** [comment]
Hey @alexhanna, do you know how long the longest article in Solr is at the moment?  Or of a relatively easy way I can find that out?

I've already got the articles that are actually in our MAI DB, so I could just use that as a guideline for how long they tend to be, but it'd be nice to know what the size range of a larger universe is...

**Comment by davidskalinder** [comment]
For my own reference: currently the biggest article in the BPP DB is 41681 characters.

**Comment by alexhanna** [comment]
I can't really find that out easily...

**Comment by davidskalinder** [comment]
> I can't really find that out easily...

Okay, probably not a big deal.  I'll check the lengths of the articles in your team's MAI DB and then figure the field should hold like double the max from both DBs.  And then watch after that I'll find out that the MySQL default is like ten times that big...

**Comment by davidskalinder** [comment]
>  I'll check the lengths of the articles in your team's MAI DB

And a mere 5 hours later: max 50884 characters (not counting the like dozen articles with bad characters in their `db_id`s).

**Comment by davidskalinder** [comment]
So:

https://chartio.com/resources/tutorials/understanding-strorage-sizes-for-mysql-text-data-types/
https://dev.mysql.com/doc/refman/8.0/en/blob.html

It looks like the 64KB `TEXT` will shave things pretty fine (and maybe even be too small if our characters are double-byte?), so the sensible choice will be the next-biggest type, `MEDIUMTEXT`, which holds 16MB.  So I think I'll add a new one of those at `article_metadata.text`, with no indexing or constraints or anything?

@alexhanna, note that on that second linked page there's some stuff about managing packet size for large fields with mysqldump in case that requires attention...

**Comment by davidskalinder** [comment]
And just after writing that, I have a pang of [naming](https://www.karlton.org/2017/12/naming-things-hard/) doubt about a column name as generic as "text" (since, like, what isn't text?).  I hate columns named "type" for the same reason and always try to come up with something more specific.

I suppose alternate options include `fulltext`, `body`, `bodytext`, and probably some others.  I can also think of two other factors that point in opposite directions:

1. The thing was already called `TEXT` in Solr, so that usage is already in the application
1. Changing the name to something like `body` would be a signal that a reference to `TEXT` is trying to use the Solr version instead of the new version
  1. Mind you, the all-caps usage already hints at this

So yeah I might have talked myself back into `text`.  But if one of you thread-watchers disagrees, speak soon or for a long time hold your peace.

**Comment by olderwoman** [comment]
Fulltext would be ok.

**Comment by davidskalinder** [comment]
> Fulltext would be ok.

I guess I'm wondering whether `text` on its own would be bad?

Also lol I guess `fulltext` shares the same describes-everything problem as `text` (when does any column contain incomplete text?).  So I think that's evidence that I'm overthinking this and should just name it `text`.

**Comment by davidskalinder** [comment]
Also, it's qualified by the table name (just like `id`).  (The problem with naming things `type` is that often a table will contain more than one thing that has a type.)  So again I think I'm being too precious and should stick with `article_metadata.text`...

**Comment by davidskalinder** [comment]
So the migration will be

```
ALTER TABLE article_metadata ADD text MEDIUMTEXT;
```

... which on its own doesn't blow up anything obvious in our dev DB, as expected.

As a reminder (to myself), text columns are automatically `DEFAULT NULL`: https://stackoverflow.com/questions/5242990/default-value-for-a-text-column

**Comment by davidskalinder** [comment]
Hmm, looks like the SQLAlchemy implementation of this will be a little slippery: https://stackoverflow.com/questions/47644739/what-column-type-does-sqlalchemy-use-for-text-on-mysql

**Comment by davidskalinder** [comment]
Okay, I think bd2da5e621c should do the trick.  I've now tested that in my dev DB with a zorch-rebuild-and-reload, and the new field looks like we want it.  (The spec in models specifies a unicode field like 20 bytes less than MySQL's `MEDIUMTEXT` just to be on the safe side.)

So this still needs merging into our testing deployment with more-real data to be sure nothing breaks, but I think it's all a-tanto...  (There will be merge conflicts, of course, since several branches add things onto the same model lines, so they should be handled by agglomerating the changes.  And it'd be nice to roll them all together to PR upstream.)

Probably best now to move on to the other stuff outstanding in #59 and test them all together.

**Comment by davidskalinder** [comment]
As of de1348deb6, this has been merged in with all the other `article_metadata` changes and can be migrated and tested with the rest as outlined in #113.  So I'ma close this.
