### ISSUE TITLE
Join timestamps into other MAI-to-pass-2 data

### ISSUE THREAD

**Issue by davidskalinder** [davidskalinder/mpeds-coder#84]
As for the timestamps, I see now that this is my mistake.  (I did all the querying and logic for them but forgot to join them in!  D'oh!)  There are timestamps for every single annotation, so instead of keeping them all my plan was to keep the earliest and latest timestamp for each coder-article pair if that sounds sensible to you?  Anyway sorry for the error, I can fix it next week before (I think?) diving into debugging the import/export settings...

_Originally posted by @davidskalinder in https://github.com/davidskalinder/mpeds-coder/issues/83#issuecomment-632818050_

**Comment by davidskalinder** [comment]
Should be fixed in 0ae763c151b.  Merged into `testing` and `master` branches.

**Comment by davidskalinder** [comment]
Tested in testing deployment

**Comment by davidskalinder** [comment]
And tested in production.  CSV looks good, except for all the other things wrong with it lol.

So @johnklemke and @olderwoman, I think the newest version of the file in `gdelt/Skalinder/MAI_exports` should have the timestamps on the far right in a format that you can play with?  The timestamps are indeed for the first and last time the coder touched the article, so let me know if we want to change that...

The timestamps do make it even more clear that for some reason a bunch of articles or events or something aren't being matched for some reason, which I'll address next in #86...  But let me know if the timestamps themselves look okay and I'll close this issue.

**Comment by davidskalinder** [comment]
So @johnklemke, I think this issue in the MAI-to-pass-2 handover file is fixed, but I can't remember whether you've done an import to pass 2 since May 26 so I can't 100% confirm that.  However this issue has been in testing for a while now, so I'm going to close it for now as part of the issue-tidying connected to #107.  Feel free to reopen if it turns out to cause any problems.

**Comment by johnklemke** [comment]
Yeah, we've done two imports for pass 2 in Access since this change and 
things look good re timestamps.

**Comment by davidskalinder** [comment]
Egg-cellent, many thanks!
